use crate::{
    AppState,
    auth::{auth_user::AuthUser, services::ADMIN_LOGROS},
    error::api_error::{ApiError, ApiResult},
    models::logro::{ChangeOrderLogro, Logro, UpdateLogro},
    repositories, utils,
};
use axum::{
    Json,
    extract::{Multipart, Path, State},
    http::StatusCode,
};
use std::{collections::HashSet, sync::Arc};

/* ==========================================================
   GET ALL
========================================================== */

pub async fn get_all_logros(State(state): State<Arc<AppState>>) -> ApiResult<Json<Vec<Logro>>> {
    let logros = repositories::logro::get_all(&state.db).await?;

    Ok(Json(logros))
}

/* ==========================================================
   GET BY ID
========================================================== */

pub async fn get_logro_by_id(
    State(state): State<Arc<AppState>>,
    Path(id): Path<i64>,
) -> ApiResult<Json<Logro>> {
    let logro = repositories::logro::get_by_id(&state.db, id)
        .await?
        .ok_or(ApiError::NotFound)?;

    Ok(Json(logro))
}

/* ==========================================================
   CREATE
========================================================== */

pub async fn create_logro(
    AuthUser(user): AuthUser,
    State(state): State<Arc<AppState>>,
    mut multipart: Multipart,
) -> ApiResult<(StatusCode, Json<Logro>)> {
    user.require(ADMIN_LOGROS)?;

    let mut titulo = String::new();
    let mut contenido = String::new();
    let mut image: Option<Vec<u8>> = None;

    while let Some(field) = multipart.next_field().await.map_err(|error| {
        eprintln!("Invalid achievement multipart body: {error}",);

        ApiError::BadRequest("Cuerpo multiparte no válido.".into())
    })? {
        match field.name() {
            Some("titulo") => {
                titulo = field
                    .text()
                    .await
                    .map_err(|_| ApiError::BadRequest("Título inválido.".into()))?;
            }

            Some("contenido") => {
                contenido = field
                    .text()
                    .await
                    .map_err(|_| ApiError::BadRequest("Contenido inválido.".into()))?;
            }

            Some("image") | Some("imagen") => {
                let bytes = field
                    .bytes()
                    .await
                    .map_err(|_| ApiError::BadRequest("Imagen inválida.".into()))?;

                if bytes.is_empty() {
                    return Err(ApiError::BadRequest("La imagen está vacía.".into()));
                }

                image = Some(bytes.to_vec());
            }

            // Order is generated by the repository.
            _ => {}
        }
    }

    let titulo = titulo.trim();
    let contenido = contenido.trim();

    validate_required_text(titulo, "El título es requerido.")?;

    validate_required_text(contenido, "El contenido es requerido.")?;

    let image = image.ok_or_else(|| ApiError::BadRequest("La imagen es requerida.".into()))?;

    /*
     * Convert before creating the database record, so a
     * malformed image cannot leave an incomplete achievement.
     */
    let avif_image = utils::image::convert_to_avif(&image).map_err(|error| {
        eprintln!(
            "Could not convert achievement image to AVIF: \
             {error}",
        );

        ApiError::BadRequest("No se pudo procesar la imagen.".into())
    })?;

    let logro = repositories::logro::create(&state.db, titulo, contenido).await?;

    let image_key = logro_image_key(logro.id);

    /*
     * Convert the R2 error to String before awaiting the
     * rollback, preventing non-Send errors across an await.
     */
    let upload_result = state
        .r2
        .upload_avif(&image_key, avif_image)
        .await
        .map_err(|error| error.to_string());

    if let Err(error_message) = upload_result {
        eprintln!(
            "Could not upload image for achievement {} to \
             R2: {}",
            logro.id, error_message,
        );

        if let Err(rollback_error) = repositories::logro::delete(&state.db, logro.id).await {
            eprintln!(
                "Could not roll back achievement {} after \
                 R2 failure: {:?}",
                logro.id, rollback_error,
            );
        }

        return Err(ApiError::InternalServerError);
    }

    Ok((StatusCode::CREATED, Json(logro)))
}

/* ==========================================================
   PATCH
========================================================== */

pub async fn patch_logro(
    AuthUser(user): AuthUser,
    State(state): State<Arc<AppState>>,
    Path(id): Path<i64>,
    mut multipart: Multipart,
) -> ApiResult<Json<Logro>> {
    user.require(ADMIN_LOGROS)?;

    let mut titulo: Option<String> = None;
    let mut contenido: Option<String> = None;
    let mut image: Option<Vec<u8>> = None;

    while let Some(field) = multipart.next_field().await.map_err(|error| {
        eprintln!("Invalid achievement multipart body: {error}",);

        ApiError::BadRequest("Cuerpo multiparte no válido.".into())
    })? {
        match field.name() {
            Some("titulo") => {
                titulo = Some(
                    field
                        .text()
                        .await
                        .map_err(|_| ApiError::BadRequest("Título inválido.".into()))?,
                );
            }

            Some("contenido") => {
                contenido = Some(
                    field
                        .text()
                        .await
                        .map_err(|_| ApiError::BadRequest("Contenido inválido.".into()))?,
                );
            }

            Some("image") | Some("imagen") => {
                let bytes = field
                    .bytes()
                    .await
                    .map_err(|_| ApiError::BadRequest("Imagen inválida.".into()))?;

                if bytes.is_empty() {
                    return Err(ApiError::BadRequest("La imagen está vacía.".into()));
                }

                image = Some(bytes.to_vec());
            }

            /*
             * Order changes must use PUT /logros/order.
             */
            _ => {}
        }
    }

    let titulo = clean_optional_text(titulo, "El título no puede estar vacío.")?;

    let contenido = clean_optional_text(contenido, "El contenido no puede estar vacío.")?;

    if titulo.is_none() && contenido.is_none() && image.is_none() {
        return Err(ApiError::BadRequest("No se enviaron cambios.".into()));
    }

    let avif_image = match image {
        Some(image) => Some(utils::image::convert_to_avif(&image).map_err(|error| {
            eprintln!(
                "Could not convert achievement image \
                         to AVIF: {error}",
            );

            ApiError::BadRequest("No se pudo procesar la imagen.".into())
        })?),

        None => None,
    };

    let update = UpdateLogro {
        titulo,
        contenido,
        orden: None,
    };

    let logro = repositories::logro::update(&state.db, id, update).await?;

    if let Some(avif_image) = avif_image {
        let image_key = logro_image_key(logro.id);

        state
            .r2
            .upload_avif(&image_key, avif_image)
            .await
            .map_err(|error| {
                eprintln!(
                    "Could not replace image for achievement \
                     {} in R2: {}",
                    logro.id, error,
                );

                ApiError::InternalServerError
            })?;
    }

    Ok(Json(logro))
}

/* ==========================================================
   CHANGE ORDER
========================================================== */

pub async fn change_order_logros(
    AuthUser(user): AuthUser,
    State(state): State<Arc<AppState>>,
    Json(request): Json<Vec<ChangeOrderLogro>>,
) -> ApiResult<StatusCode> {
    user.require(ADMIN_LOGROS)?;

    if request.is_empty() {
        return Err(ApiError::BadRequest(
            "Debe proporcionar al menos un logro.".into(),
        ));
    }

    let mut ids = HashSet::new();
    let mut orders = HashSet::new();

    for item in &request {
        if item.orden < 0 {
            return Err(ApiError::BadRequest(
                "El orden no puede ser negativo.".into(),
            ));
        }

        if !ids.insert(item.id) {
            return Err(ApiError::BadRequest("Id de logro duplicado.".into()));
        }

        if !orders.insert(item.orden) {
            return Err(ApiError::BadRequest("Orden duplicado.".into()));
        }
    }

    repositories::logro::change_order(&state.db, request).await?;

    Ok(StatusCode::NO_CONTENT)
}

/* ==========================================================
   DELETE
========================================================== */

pub async fn delete_logro(
    AuthUser(user): AuthUser,
    State(state): State<Arc<AppState>>,
    Path(id): Path<i64>,
) -> ApiResult<Json<Logro>> {
    user.require(ADMIN_LOGROS)?;

    let logro = repositories::logro::delete(&state.db, id).await?;

    let image_key = logro_image_key(logro.id);

    /*
     * The database record is already gone. An R2 deletion
     * error should not falsely report that the achievement
     * still exists.
     */
    if let Err(error) = state.r2.delete_object(&image_key).await {
        eprintln!(
            "Could not delete R2 image for achievement {}: {}",
            logro.id, error,
        );
    }

    Ok(Json(logro))
}

/* ==========================================================
   PRIVATE HELPERS
========================================================== */

fn logro_image_key(logro_id: i64) -> String {
    format!("img_logros/{logro_id}.avif",)
}

fn validate_required_text(value: &str, message: &str) -> ApiResult<()> {
    if value.is_empty() {
        return Err(ApiError::BadRequest(message.to_string()));
    }

    Ok(())
}

fn clean_optional_text(value: Option<String>, empty_message: &str) -> ApiResult<Option<String>> {
    value
        .map(|value| {
            let value = value.trim().to_string();

            if value.is_empty() {
                return Err(ApiError::BadRequest(empty_message.to_string()));
            }

            Ok(value)
        })
        .transpose()
}
